### PR TITLE
Move eslint dependencies to devDependencies

### PR DESCRIPTION
**Pull request by srcrawford**
### Description

Small change - Move eslint dependencies to devDependencies as consumers will pull in eslint and eslint-config-loopback

#### Related issues

- connect to #86

### Checklist

- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by virkt25** [comment]
ok to test

**Comment by virkt25** [comment]
Hi @srcrawford, The PR was failing on Node 4. I just landed a PR to drop Node 4. Can you please rebase this PR and I can help you land this + do a release. Thanks for the contribution.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Pull request closed without merging**
