### PR TITLE
Cleaning up obsolete or unused files & dependencies

### PR DESCRIPTION
**Pull request by glesage**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
LGTM

**Comment by glesage** [comment]
Yea this was just a small cleanup before I started getting onto https://github.com/strongloop/loopback-connector-remote/pull/30 :P

**Comment by superkhau** [comment]
@glesage Thanks for the contribution! ;)

**Pull request merged**
