### PR TITLE
Fixes to relations

### LINKED ISSUE #42: Include filter does not work
It is not possible to `include` a remote model's relation. For example, consider models called `Trip` and `Country`, where:
1.  `Trip` belongsTo `Country`
2.  These models exist in both a local app and a remote LB app.
3. In the local app, these models are backed by a datasource configured w/ the remote connector.

When a query is performed with an include filter (`Trip.findOne({include: 'country' })`, a remote call is made: `GET /api/Trips/findOne?filter[include]=country`. The remote service dutifully returns the Trip instance with an additional `country` property. Despite this, the resulting instance on the local app does not contain the relational data.

The reason for this is straight forward - `loopback-connector-remote` coerces result data into the target model by simply instantiating it (`new Model(payload)`), which for strict models will strip any unrecognized properties. This line: https://github.com/strongloop/loopback-connector-remote/blob/master/lib/remote-connector.js#L83

The solution should be to expand the type handler to prime the relation cache (`__cachedRelations`), allowing the resulting model to track the relational data.

### PR DESCRIPTION
**Pull request by doublemarked**
Fixes a couple issues with relations, including issues #42 and #12:
1. Fixes the include filter by improving type coercion. Remote type coercion now also seeds `__cachedRelations` and `__data` to ensure that returned relations are available in the calling project.
2. Fixed relation cache (necessary to fully fix #42) by removing the relation mixin's defineRelationProperty entirely. 

Regarding this PR - the second item above fixes the problems with the cache, and in my eye appears to remove an unnecessary mucking that this connector was doing - the previous code's (`defineRelationProperty`) practice of directly mapping the relationship methods to the REST-interface methods (`__get__relation`, etc) is causing of all the juggler relation logic being skipped, including the cache.

That said, I'm not deeply aware of the design goals of this module, and it's possible this is violating a principle of its design by introducing methods that are not 1:1 mapping to REST endpoints. This uncertainty is compounded by the shallow set of existing tests (which I resisted the urge to improve). 

That said, I do feel that this change makes the connector adhere more honestly to the connector specification, a problem which is causing trouble for implementers. I welcome any feedback and will be ready to improve this PR as necessary.

Note: Please also see my notes about caching in the Issue #42 discussion: https://github.com/strongloop/loopback-connector-remote/issues/42#issuecomment-213851629

connect to strongloop/loopback-connector-remote#42

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by richardpringle** [comment]
ok to test

**Comment by doublemarked** [comment]
Hm, not sure what to make of the build failure on Amazon w/ Node v4, where the request module fails to load one of its internal files,
```
Error: Cannot find module './lib/getProxyFromURI'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/node-4.x/lib/node_modules/npm/node_modules/request/request.js:22:23)
```

**Comment by richardpringle** [comment]
Yeah, I believe that we can ignore that failure. I'll try triggering the build again a little later.

**Comment by bajtos** [comment]
@richardpringle I am afraid I am not very familiar with this codebase yet. @superkhau or @raymondfeng, could you please review?

**Comment by superkhau** [comment]
I am also not familiar enough with this codebase. @raymondfeng or @ritch would need to take this one.

**Comment by ritch** [comment]
> That said, I'm not deeply aware of the design goals of this module

The goals are pretty much:

 - allow transport agnostic communication between loopback applications
 - make an effort to not invoke remote methods when unnecessary
 - support the same local API as remote methods, allowing code to move from lb app to lb

>  the previous code's (defineRelationProperty) practice of directly mapping the relationship methods to the REST-interface methods (__get__relation, etc) 

This is actually something we can't change without some discussion. We (@kraman and I) specifically did it this way so that the remote connector would invoke the relation endpoint and not the model's endpoint. Here is a basic example.

```js
Author.hasMany(Comment);
Comment.attachTo(remoteDataSource);
Author.attachTo(remoteDataSource);

Author.findOne(function(err, author) {
  // this could make 2 requests to get at the data
  author.comments(console.log);
  // 1) GET /comments?filter[where][authorId]=${author.id}
  // 2) GET /authors/${author.id}/comments
});
```

AFAICT this PR's change would make the 1 style request. This will work for some cases, but requires you to make the `Comment` model `public`.

The 2 style is required so that LoopBack and your implementation know that the request is for related data.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by doublemarked** [comment]
Rich, many many thanks for the detailed explanation and feedback. I will scale back these changes a bit to help w/ the include issue without changing so much of the role of the connector.

**Comment by bajtos** [comment]
@doublemarked ping, what's the status of this pull request?

**Comment by doublemarked** [comment]
@bajtos hey, sorry I think this PR should be abandoned. We've long ago given up on this connector and I don't honestly know which of the changes in this PR are still relevant or desired.

**Comment by bajtos** [comment]
@doublemarked Makes sense, thank you for letting us know.

Out of curiosity, what are you using instead of this connector?

**Comment by doublemarked** [comment]
We were using it for communication between LB microservices but decided that the complexity of that wasn't necessary or worthwhile at that point and merged everything back to a single backend service.

**Pull request closed without merging**
