### PR TITLE
Move eslint dependencies to devDependencies

### PR DESCRIPTION
**Pull request by srcrawford**
### Description

Small change - Move eslint dependencies to devDependencies as consumers will pull in eslint and eslint-config-loopback

#### Related issues

- connect to #86

### Checklist

- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by srcrawford** [comment]
@virkt25 Apologies I had to create this second PR (after closing #87) with proper rebase - thanks for handling the fix to pipeline - hope this PR is ok, if you could review please.. thanks

**Comment by virkt25** [comment]
ok to test

**Comment by virkt25** [comment]
Thanks for the contribution @srcrawford!! And no worries with closing / opening a new PR. Your changes have landed and released as version 3.4.0. Looking forward to seeing more contributions from you in the future :)

**Pull request merged**
