### PR TITLE
Fix remote relations

### PR DESCRIPTION
**Pull request by glesage**
It seems the remote datasource connector does not allow `include: relation`

I've written a few tests that currently show how it does not work... though I have yet to figure out how to fix it.

I was hoping it would show "failing tests" under the github status

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by glesage** [comment]
Its not actually supposed to pass currently... the 1 test that matters fails, not sure how or why or how to fix it but I will attempt.. and welcome any tips (:

We really need this at the company I work at...

This https://github.com/glesage/loopback-connector-remote/blob/fix-remote-relations/test/relations.test.js#L60 fails

**Comment by drywolf** [comment]
I'm currently also onto that bug, what I did for a experimental fix was to add the following code to the relations mixin (at https://github.com/strongloop/loopback-connector-remote/blob/master/lib/relations.js#L209)

      var scope = function() {
		  var cached = that.__cachedRelations[def.name];
		  
		  if (arguments.length == 0)
			  return cached;
		  
        return that['__get__' + def.name].apply(that, arguments);
      };

it simply checks if the relation property function is being called without any parameters and returns the cached data if it is available.
I'm not very experienced with the code though, so I can't tell if this is the right way to fix this issue or if the __cachedRelations should be fetched in a different place instead.

**Comment by glesage** [comment]
Hm ok awesome, I'm not either... I've actually got a current pull request open with a failing test to demonstrate the issue exactly...

I'll run it with your fix see if the issue is resolved with this.. temporarily

https://github.com/strongloop/loopback-connector-remote/pull/33

**Pull request closed without merging**
