### PR TITLE
Do not use native promises in tests

### PR DESCRIPTION
**Pull request by superkhau**
- Refactor some tests to use bluebird for promise impl
- Fix based on comments at https://github.com/strongloop/loopback-connector-remote/pull/44/files#r61875179
- Add tests to integration dir (organized/named by feature)

### CODE REVIEW

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@bajtos Review please.

**Comment by bajtos** [comment]
LGTM.

**Comment by bajtos** [comment]
@superkhau actually, I take that LGTM back. Since you added a new test file `test/integration/promise-support.js`, are you sure it will be picked up by mocha? I believe it picks only files directly in `test` directory, it does not recurse by default.

IIRC, we agreed that the `"test"` script should be modified to something like this:

```
"test": "mocha test/unit/*.js test/integration/*.js"
```

In this particular case, since we don't have `test/unit` yet, I think this may work well?

```
"test": "mocha test/*.js test/integration/*.js"
```

Thoughts?

**Comment by bajtos** [comment]
@superkhau apparently this repo uses `grunt` to run tests, so you will need to make changes in `Gruntfile` instead.

Here is the current wildcard for unit tests:
https://github.com/strongloop/loopback-connector-remote/blob/7957084a243ac108d853fded89b3d04a855bdf5f/Gruntfile.js#L32

I think you should define new targets. We have `unit` and `unit-xml` now, add `integration` and `integration-xml`? Also make sure to include `integration-xml` in the task started by CI builds.

**Comment by superkhau** [comment]
You are right, it wasn't running via Grunt earlier. I fixed it all now though so please review and merge it directly yourself as I will be on vacation by the time you read this.

**Comment by superkhau** [comment]
>...In this particular case, since we don't have test/unit yet, I think this may work well?

I will make it work with grunt for now. But we should add a bullet point to the CI refactor tasks to remove Grunt+Gulp from all repos (along with the Makefiles task). For now, this is good enough.

**Comment by superkhau** [comment]
Actually I already have a note about the Gulp/Grunt thing here: https://github.com/strongloop-internal/scrum-loopback/issues/872#issuecomment-219799829

**Comment by bajtos** [comment]
Looks good now, I am going to land this. Thank you!

**Pull request merged**
