### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by superkhau**
Connect to https://github.com/strongloop/loopback-connector-remote/pull/30

### CODE REVIEW

**Comment by glesage** [comment]
Hey btw I think we may need to add `grunt-cli` to dev-dependencies

**Comment by superkhau** [comment]
>Hey btw I think we may need to add grunt-cli to dev-dependencies

Added.

**Comment by superkhau** [comment]
@glesage I merged it in. Some dependents are failing, but they are unrelated to your changes. Thanks for the contribution! ;)

**Comment by glesage** [comment]
Ok I see awesome thanks!

**Pull request merged**
