### PR TITLE
Adding power support

### PR DESCRIPTION
**Pull request by lysannef**
### Description
Enabling support on power (ppc64le) architecture.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Hi @lysannef, thank you for the pull request (and https://github.com/strongloop/loopback-component-explorer/pull/264 too). Before we go forward to add power/ppc64le target to all of our builds, I'd like to better understand your intentions. What kind of HW are you trying to run LoopBack on?

This repository belongs to LoopBack 3, which is in LTS mode. If we all agree to start supporting power/ppc64le in LoopBack, then I'd prefer to start from LoopBack 4, see https://github.com/strongloop/loopback-next

I think it would be best if you could open a new issue where we can discuss the overall plan for this initiative.

/cc @dhmlau @raymondfeng

**Comment by lysannef** [comment]
@bajtos  So the intention was to add Power architectures to your CI environment. Using the linux-ppc64le parameter in the travis.yml config file, we are able to run extend the CI environment for loopback-connector-remote to ppc64le systems.

It triggers build jobs for  loopback-connector-remote on the ppc64le base architecture. The build passes on these systems hence we raised a PR for adding official power support in the CI environment for Loopback.

**Comment by bajtos** [comment]
> So the intention was to add Power architectures to your CI environment. 

Sure, I understand that part. Here is what I don't understand: what computers are running on Power these days? Is this needed to support IBM Mainframes? Something else? Why should we invest our limited time to maintain support for the Power architecture in LoopBack, as opposed to working on other features instead?

Anyhow, as I mentioned, LoopBack 3.x is in LTS mode where we are not adding new features. 

Could you please open a new pull request to add support for `linux-ppc64le` to [loopback-next](https://github.com/strongloop/loopback-next) instead?

If you are working at IBM, then feel free to reach out to us via our company-wide Slack channel `#loopback-at-ibm`, where we can discuss this in private and in a faster pace.

**Pull request closed without merging**
