### PR TITLE
Move sl-blip download to optionalDependencies

### PR DESCRIPTION
**Pull request by googol**
This follows the style used in other strongloop packages, and can be
disabled by the user by using --no-optional.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by richardpringle** [comment]
@bajtos, what happened to sl-blip in the end? we got rid of it didn't we?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
It is officially removed. Closing in favour of https://github.com/strongloop/loopback-connector-remote/pull/41

**Pull request closed without merging**
