### PR TITLE
Remote relations override issue

### PR DESCRIPTION
**Pull request by glesage**
It seems remote datasource overrides relations... See the last test of the suite

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by glesage** [comment]
Its not actually supposed to pass currently... the 1 test that matters fails, not sure how or why or how to fix it but I will attempt.. and welcome any tips (:

We really need this at the company I work at...

This https://github.com/glesage/loopback-connector-remote/blob/fix-remote-relations/test/relations.test.js#L60 fails

**Comment by glesage** [comment]
Ok NOW I actually have the error I'm looking for... its not including things even though the relations is setup right and models are created right

**Comment by glesage** [comment]
@superkhau let me know if you have any ideas

**Comment by glesage** [comment]
Ok the test is setup correctly to test only what matters: find with include
It seems its not including things even though the relations is setup right and models are created right

@superkhau let me know if you have any ideas

**Comment by glesage** [comment]
Is this behavior normal or should it be fixed? I'm not sure I guess...

**Comment by superkhau** [comment]
@slnode test please

**Comment by glesage** [comment]
hey @superkhau the build isn't going to pass, there's an error in there on purpose just to show you guys what I mean with the relation override...

**Comment by superkhau** [comment]
@glesage Hello, its been awhile. ;) Do you want to submit the fix along with the faling test?

**Comment by glesage** [comment]
Not exactly I was wondering if the issue that this brings up is on purpose or whether its actually a bug (:

**Comment by glesage** [comment]
Hey @superkhau any updates? The current behavior is that remote relations are overriden when defined on the remote app... This test shows that behavior and I'm just wondering if this is on purpose or not.

**Comment by superkhau** [comment]
@glesage Sorry for the late response. I do not know the answer to this question.

>The current behavior is that remote relations are overriden when defined on the remote app... This test shows that behavior and I'm just wondering if this is on purpose or not.

@raymondfeng Is this by design?

**Comment by superkhau** [comment]
@raymondfeng Ping.

**Comment by bajtos** [comment]
Hello @glesage, sorry for the long delay. Is this pull request still relevant?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
> It seems remote datasource overrides relations... See the last test of the suite

Does the following https://github.com/strongloop/loopback-connector-remote/pull/43#issuecomment-216970151 perhaps provide enough explanation?

**Comment by bajtos** [comment]
I am closing this pull request as abandoned.

**Pull request closed without merging**
