### PR TITLE
proposal to parse to Date the strings that has the appropiate format

### PR DESCRIPTION
**Pull request by danilat**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hello @danilat, sorry for the long silence on our side. Is this pull request still relevant?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by danilat** [comment]
I'm not sure, at this time I don't work with loopback anymore :S

**Comment by bajtos** [comment]
> I'm not sure, at this time I don't work with loopback anymore

No worries, thank you for letting us know.

I'll close this pull request as abandoned then.

**Pull request closed without merging**
